version: '3'
services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - /var/lib/postgresql/data
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./db-react-webapp
    volumes:
      - /app/node_modules
      - ./db-react-webapp:/app
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./db-connect-server
    volumes:
      # - /app/node_modules # uncomment this in prod 
      - ./db-connect-server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
